databases:
  - name: ai-qa-db
    plan: free
    databaseName: tcgen

services:
  - type: web
    name: ai-qa-assistant
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_URL
        fromDatabase:
          name: ai-qa-db
          property: jdbcConnectionString
      - key: DB_USER
        fromDatabase:
          name: ai-qa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ai-qa-db
          property: password
